# Generated by Django 4.2.1 on 2023-05-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentData',
            new_name='StudentData1',
        ),
    ]
